services:
  tanyaustadz:
    build: .
    restart: unless-stopped
    container_name: tanyaustadz
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - .env
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env.postgres
    ports:
      - 5432:5432
