volumes:
  go-mod:
  go-build:

services:
  tanyaustadz:
    build:
      target: base
    environment:
      PWD: ${PWD:-/src}
    volumes:
      - go-mod:/go/pkg/mod
      - go-build:/root/.cache/go-build
      - ${PWD:-.}:${PWD:-/src}
    working_dir: ${PWD:-/src}
    entrypoint: [go, run, ./]
